In [1]:

import warnings
warnings.filterwarnings('ignore')

In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


irisData = pd.read_csv('./iris_data.csv')

#print(irisData.head)
features = irisData[["SepalLength","SepalWidth","PetalLength","PetalWidth"]]
targetVariables = irisData.Class 

featureTrain, featureTest, targetTrain, targetTest = train_test_split(features, targetVariables, test_size=.2)

model = DecisionTreeClassifier()
fittedModel = model.fit(featureTrain, targetTrain)
predictions = fittedModel.predict(featureTest)





In [5]:
print(confusion_matrix(targetTest, predictions))

[[11  0  0]
 [ 0  6  1]
 [ 0  0 12]]


In [13]:
print(accuracy_score(targetTest, predictions)*100)

96.66666666666667


In [6]:
# Let us move in details now - This code below takes 20 minutes to execute for the first time

In [7]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import cross_validation

data = pd.read_csv('./iris_data.csv')

print(data)
data.features = data[["SepalLength","SepalWidth","PetalLength","PetalWidth"]]
data.targets = data.Class 

feature_train, feature_test, target_train, target_test = train_test_split(data.features, data.targets, test_size=.2)

model = DecisionTreeClassifier(criterion='gini')
model.fitted = model.fit(feature_train, target_train)
model.predictions = model.fitted.predict(feature_test)

print(confusion_matrix(target_test, model.predictions))
print(accuracy_score(target_test, model.predictions))



     SepalLength  SepalWidth  PetalLength  PetalWidth            Class
0            5.1         3.5          1.4         0.2      Iris-setosa
1            4.9         3.0          1.4         0.2      Iris-setosa
2            4.7         3.2          1.3         0.2      Iris-setosa
3            4.6         3.1          1.5         0.2      Iris-setosa
4            5.0         3.6          1.4         0.2      Iris-setosa
5            5.4         3.9          1.7         0.4      Iris-setosa
6            4.6         3.4          1.4         0.3      Iris-setosa
7            5.0         3.4          1.5         0.2      Iris-setosa
8            4.4         2.9          1.4         0.2      Iris-setosa
9            4.9         3.1          1.5         0.1      Iris-setosa
10           5.4         3.7          1.5         0.2      Iris-setosa
11           4.8         3.4          1.6         0.2      Iris-setosa
12           4.8         3.0          1.4         0.1      Iris-setosa
13    

In [8]:
predicted = cross_validation.cross_val_predict(model,data.features,data.targets, cv=10)
print(accuracy_score(data.targets,predicted))

0.9533333333333334


# Use the IRIS dataset from internet instead - needs internet connections

In [9]:
from sklearn import datasets
dataset = datasets.load_iris()

In [10]:
features=dataset.data

In [25]:
#features

In [11]:
targets=dataset.target

In [14]:
feature_train, feature_test, target_train, target_test = train_test_split(features, targets, test_size=.2)
# Change this line from previous codes to reflect features and targets
model = DecisionTreeClassifier(criterion='gini')
model.fitted = model.fit(feature_train, target_train)
model.predictions = model.fitted.predict(feature_test)

print(confusion_matrix(target_test, model.predictions))
print(accuracy_score(target_test, model.predictions))

[[10  0  0]
 [ 0 10  1]
 [ 0  3  6]]
0.8666666666666667
